### ISSUE TITLE
Jupyter Notebook

### ISSUE THREAD

**Issue by RabeaMue** [BBeulmann/Bdk-Library_Carpentry_Aufgabenset_1_BJOERN_BEULMANN#1]
Hallo Björn,
habe keinen Fehler gefunden. Sieht sehr gut aus! :)

Liebe Grüße,
Rabea

**Comment by RabeaMue** [comment]
Lediglich bei [7] und [9] hast du ein Leerzeichen zwischen print und der Klammer. Das Ergebnis wird dadurch nicht falsch, entspricht aber nicht dem Python Style Guide.

**Comment by BBeulmann** [comment]
Herzlichen Dank! Die Leerzeichen habe ich entfernt, die Klammern werden bei mir nun auch in grün dargestellt.
LG Björn
