### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by RabeaMue** [BBeulmann/Bdk-Library_Carpentry_Aufgabenset_1_BJOERN_BEULMANN#4]
Hallo Björn,

habe in deinem Skript keine Fehler gefunden. 
LG Rabea

**Comment by BBeulmann** [comment]
Hallo Rabea!
Vielen Dank für Dein Feedback, das freut zu hören. Ich habe gerade noch die Fragestellungen mit in das Skript aufgenommen und gegendert, das hätte ich fast vergessen.

LG Björn
